PRAGMA foreign_keys = off;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS PERGUNTA (ID INTEGER PRIMARY KEY NOT NULL, DESCRICAO STRING NOT NULL, LEVEL CHAR (1, 1) NOT NULL);
INSERT INTO PERGUNTA (ID, DESCRICAO, LEVEL) VALUES (1, 'Qual é a distância entre a marca penal e a linha de gol?', 'F');
INSERT INTO PERGUNTA (ID, DESCRICAO, LEVEL) VALUES (2, 'Qual é a largura mínima do campo de jogo?', 'F');
INSERT INTO PERGUNTA (ID, DESCRICAO, LEVEL) VALUES (3, 'As redes de meta...', 'F');

-- Table: ALTERNATIVA
CREATE TABLE IF NOT EXISTS ALTERNATIVA (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, PERGUNTA_ID INTEGER CONSTRAINT fk_pergunta_alternativa REFERENCES PERGUNTA (ID), DESCRICAO STRING (0) NOT NULL, CORRETA BOOLEAN NOT NULL DEFAULT false);
INSERT INTO ALTERNATIVA (ID, PERGUNTA_ID, DESCRICAO, CORRETA) VALUES (4, 1, '10m (11 jardas)', 'false');
INSERT INTO ALTERNATIVA (ID, PERGUNTA_ID, DESCRICAO, CORRETA) VALUES (5, 1, '11m (12 jardas)', 'true');
INSERT INTO ALTERNATIVA (ID, PERGUNTA_ID, DESCRICAO, CORRETA) VALUES (6, 1, '9m (10 jardas)', 'false');
INSERT INTO ALTERNATIVA (ID, PERGUNTA_ID, DESCRICAO, CORRETA) VALUES (7, 1, '12m (13 jardas)', 'false');
INSERT INTO ALTERNATIVA (ID, PERGUNTA_ID, DESCRICAO, CORRETA) VALUES (8, 2, '45m (50 jardas)', 'true');
INSERT INTO ALTERNATIVA (ID, PERGUNTA_ID, DESCRICAO, CORRETA) VALUES (9, 2, '50m (55 jardas)', 'false');
INSERT INTO ALTERNATIVA (ID, PERGUNTA_ID, DESCRICAO, CORRETA) VALUES (10, 2, '40m (45 jardas)', 'false');
INSERT INTO ALTERNATIVA (ID, PERGUNTA_ID, DESCRICAO, CORRETA) VALUES (11, 2, '55m (60 jardas)', 'false');
INSERT INTO ALTERNATIVA (ID, PERGUNTA_ID, DESCRICAO, CORRETA) VALUES (12, 3, 'Devem estar presas.', 'false');
INSERT INTO ALTERNATIVA (ID, PERGUNTA_ID, DESCRICAO, CORRETA) VALUES (13, 3, 'Podem ser utilizadas, de acordo com o regulamento da competição.', 'false');
INSERT INTO ALTERNATIVA (ID, PERGUNTA_ID, DESCRICAO, CORRETA) VALUES (14, 3, 'Devem estar presas às metas e no solo atrás da mesma.', 'true');
INSERT INTO ALTERNATIVA (ID, PERGUNTA_ID, DESCRICAO, CORRETA) VALUES (15, 3, 'São obrigatórias.', 'false');
COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
